-- Run this migration in Supabase SQL Editor.
-- The frontend must use only the publishable key. Never expose service_role.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  first_name text not null default '',
  last_name text not null default '',
  avatar_url text,
  phone text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  price numeric(10, 2) not null check (price >= 0),
  description text not null default '',
  category text not null default 'general',
  image text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Saved address',
  address text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.carts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'Processing',
  total numeric(10, 2) not null check (total >= 0),
  delivery_address text not null,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists addresses_user_id_idx on public.addresses(user_id);
create index if not exists orders_user_id_idx on public.orders(user_id);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.addresses enable row level security;
alter table public.carts enable row level security;
alter table public.orders enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated using (id = auth.uid());
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "profiles_update_own" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "products_public_read" on public.products;
create policy "products_public_read" on public.products for select to anon, authenticated using (true);

drop policy if exists "addresses_own" on public.addresses;
create policy "addresses_own" on public.addresses for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "carts_own" on public.carts;
create policy "carts_own" on public.carts for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "orders_select_own" on public.orders;
drop policy if exists "orders_insert_own" on public.orders;
drop policy if exists "orders_update_own" on public.orders;
create policy "orders_select_own" on public.orders for select to authenticated using (user_id = auth.uid());
create policy "orders_update_own" on public.orders for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Orders are created through the server-side pricing function below. The
-- browser can only update an owner's delivery address after creation.
revoke insert on public.orders from anon, authenticated;
revoke update on public.orders from anon, authenticated;
grant update (delivery_address) on public.orders to authenticated;

create or replace function public.create_order(
  p_delivery_address text,
  p_items jsonb,
  p_tip numeric default 0,
  p_coupon_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  item jsonb;
  item_id bigint;
  item_qty integer;
  item_count integer := 0;
  product_row record;
  canonical_items jsonb := '[]'::jsonb;
  subtotal numeric(10, 2) := 0;
  delivery_fee numeric(10, 2) := 4.78;
  normalized_coupon text := nullif(upper(trim(coalesce(p_coupon_code, ''))), '');
  coupon_discount numeric(10, 2) := 0;
  calculated_total numeric(10, 2);
  inserted_order public.orders;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if p_delivery_address is null or length(trim(p_delivery_address)) = 0 or length(p_delivery_address) > 500 then
    raise exception 'Invalid delivery address';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 100 then
    raise exception 'Invalid order items';
  end if;

  if p_tip is null or p_tip < 0 or p_tip > 100 then
    raise exception 'Invalid tip';
  end if;

  for item in select value from jsonb_array_elements(p_items) loop
    item_count := item_count + 1;
    if jsonb_typeof(item) <> 'object'
      or not (item ? 'id')
      or not (item->>'id' ~ '^[0-9]+$')
      or not (item ? 'qty')
      or not (item->>'qty' ~ '^[0-9]+$') then
      raise exception 'Invalid order item';
    end if;

    item_id := (item->>'id')::bigint;
    item_qty := (item->>'qty')::integer;
    if item_id < 1 or item_qty < 1 or item_qty > 100 then
      raise exception 'Invalid order item quantity';
    end if;

    select id, title, price, category, image
      into product_row
      from public.products
     where id = item_id;
    if not found then
      raise exception 'Product is not available';
    end if;

    subtotal := subtotal + (product_row.price * item_qty);
    canonical_items := canonical_items || jsonb_build_array(jsonb_build_object(
      'id', product_row.id,
      'title', product_row.title,
      'img', product_row.image,
      'price', product_row.price,
      'qty', item_qty,
      'category', product_row.category
    ));
  end loop;

  if normalized_coupon = 'HOSGELDIN20' and subtotal >= 100 then
    coupon_discount := round(subtotal * 0.20, 2);
  elsif normalized_coupon = 'KARGOBEDAVA' and subtotal >= 200 then
    coupon_discount := delivery_fee;
  elsif normalized_coupon = 'YAZ2026' and subtotal >= 75 then
    coupon_discount := round(subtotal * 0.15, 2);
  elsif normalized_coupon = 'OZEL50' and subtotal >= 250 then
    coupon_discount := 50;
  end if;

  calculated_total := greatest(0, round(subtotal + delivery_fee + p_tip - coupon_discount, 2));

  insert into public.orders (user_id, status, total, delivery_address, items)
  values (current_user_id, 'Processing', calculated_total, trim(p_delivery_address), canonical_items)
  returning * into inserted_order;

  return jsonb_build_object(
    'id', inserted_order.id,
    'status', inserted_order.status,
    'total', inserted_order.total,
    'delivery_address', inserted_order.delivery_address,
    'items', inserted_order.items,
    'created_at', inserted_order.created_at
  );
end;
$$;

revoke all on function public.create_order(text, jsonb, numeric, text) from public, anon;
-- Keep checkout closed until a trusted payment webhook confirms the charge.
revoke execute on function public.create_order(text, jsonb, numeric, text) from authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, first_name, last_name, avatar_url, phone)
  values (
    new.id,
    new.raw_user_meta_data ->> 'username',
    coalesce(new.raw_user_meta_data ->> 'firstName', ''),
    coalesce(new.raw_user_meta_data ->> 'lastName', ''),
    new.raw_user_meta_data ->> 'avatarUrl',
    coalesce(new.raw_user_meta_data ->> 'phone', '')
  ) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
