import { useEffect, useState, type FormEvent } from "react";
import { useAuth } from "../../features/auth/AuthContext";
import { loadSavedCards, saveSavedCards } from "../../features/payments/savedCards";
import { useCardForm } from "../../features/payments/useCardForm";
import { CardThemeSelector } from "../../components/payments";
import type { PaymentCard } from "../../types/payment";

const inputClass = "w-full rounded-xl border border-[#ddd] px-3 py-3 text-sm outline-none focus:border-[#b6349a] focus:ring-2 focus:ring-[#b6349a]/[.12]";

export default function MyPayments() {
  const { user } = useAuth();
  const [cards, setCards] = useState<PaymentCard[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [cardToDelete, setCardToDelete] = useState<PaymentCard | null>(null);
  const [toastMessage, setToastMessage] = useState("");
  const { formData, errors, handleNameChange, handleCardNumberChange, handleExpiryChange, handleCvvChange, validateForm, createCard, setTheme, resetForm } = useCardForm();
  useEffect(() => setCards(loadSavedCards(user)), [user]);
  const toast = (message: string) => { setToastMessage(message); setTimeout(() => setToastMessage(""), 3500); };
  const handleAdd = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!validateForm()) return; const next = [createCard(cards.length === 0), ...cards]; setCards(next); saveSavedCards(user, next); resetForm(); setIsModalOpen(false); toast("Kart görünümü kaydedildi (demo). Gerçek ödeme alınmaz."); };
  const setDefault = (id: PaymentCard["id"]) => { const next = cards.map((card) => ({ ...card, isDefault: card.id === id })); setCards(next); saveSavedCards(user, next); toast("Varsayılan ödeme kartınız güncellendi."); };
  const removeCard = () => { if (!cardToDelete) return; let next = cards.filter((card) => String(card.id) !== String(cardToDelete.id)); if (next.length && !next.some((card) => card.isDefault)) next = next.map((card, index) => index === 0 ? { ...card, isDefault: true } : card); setCards(next); saveSavedCards(user, next); setCardToDelete(null); toast("Kart başarıyla silindi."); };

  return <div className="w-full">
    {toastMessage && <div className="fixed bottom-6 right-6 z-50 rounded-xl bg-[#111] px-4 py-3 text-sm font-semibold text-white shadow-lg">{toastMessage}</div>}
    <div className="mb-8 flex items-start justify-between gap-4 max-sm:flex-col"><div><h2 className="text-[28px] font-extrabold text-[#111]">Ödeme Yöntemlerim</h2><p className="mt-2 text-sm text-[#777]">Demo kart görünümlerinizi yönetin. Bu ekranda gerçek ödeme yapılmaz.</p></div><button type="button" onClick={() => { resetForm(); setIsModalOpen(true); }} className="rounded-lg bg-[#b6349a] px-4 py-2.5 text-sm font-semibold text-white">+ Yeni Kart Ekle</button></div>
    <div className="grid gap-5 md:grid-cols-2">
      {cards.map((card) => <article key={card.id} className="overflow-hidden rounded-2xl border border-[#eee] bg-white p-4 shadow-sm"><div className="relative min-h-48 rounded-2xl p-5 text-white shadow-lg" style={{ background: card.theme === "midnight" ? "linear-gradient(135deg,#111827,#374151)" : card.theme === "ocean" ? "linear-gradient(135deg,#0369a1,#22d3ee)" : "linear-gradient(135deg,#b6349a,#831843)" }}><div className="flex justify-between text-xs opacity-80"><span>{card.isDefault ? "Varsayılan Kart" : "E-Store Card"}</span><span>{card.cardType?.toUpperCase()}</span></div><div className="mt-12 font-mono text-lg tracking-wider">{card.maskedNumber}</div><div className="mt-6 flex justify-between text-xs"><span><small className="block opacity-70">KART SAHİBİ</small>{card.cardHolder}</span><span><small className="block opacity-70">SON KULLANMA</small>{card.expiry}</span></div></div><div className="mt-3 flex items-center justify-between"><button type="button" onClick={() => setDefault(card.id)} disabled={card.isDefault} className="text-xs font-semibold text-[#b6349a] disabled:text-[#999]">{card.isDefault ? "Aktif Varsayılan" : "Varsayılan Yap"}</button><button type="button" onClick={() => setCardToDelete(card)} className="text-xs font-semibold text-red-600">Sil</button></div></article>)}
      {cards.length === 0 && <div className="rounded-2xl border border-dashed border-[#ddd] p-8 text-center text-sm text-[#777]">Kayıtlı kartınız bulunmuyor.</div>}
      <button type="button" onClick={() => { resetForm(); setIsModalOpen(true); }} className="flex min-h-48 flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#d9b4d0] bg-[#fff8fd] p-6 text-center"><span className="text-3xl text-[#b6349a]">+</span><strong className="mt-2 text-[#333]">Yeni Kart Ekle</strong><span className="mt-1 text-xs text-[#777]">Kredi veya banka kartı ekleyerek hızlı ödeme yapın</span></button>
    </div>
    <div className="mt-6 flex gap-3 rounded-2xl border border-green-100 bg-green-50 p-4 text-sm text-green-800"><span>🔒</span><p className="m-0"><strong>Demo Kart Görünümü</strong><br />Yalnızca maskelenmiş kart numarası tarayıcıda saklanır. Gerçek kart bilgisi girmeyin.</p></div>

    {isModalOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" onClick={() => setIsModalOpen(false)}><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="mb-5 flex justify-between border-b border-[#eee] pb-4"><h3 className="text-lg font-bold text-[#111]">Yeni Kart Ekle</h3><button type="button" onClick={() => setIsModalOpen(false)} className="text-xl text-[#777]">×</button></div><div className="mb-5 rounded-2xl p-5 text-white" style={{ background: "linear-gradient(135deg,#b6349a,#831843)" }}><div className="flex justify-between text-xs"><span>E-Store Card</span><span>{formData.cardNumber || "•••• •••• •••• ••••"}</span></div><div className="mt-10 flex justify-between text-xs"><span>{formData.cardHolder || "KART SAHİBİ"}</span><span>{formData.expiry || "AA/YY"}</span></div></div><form onSubmit={handleAdd} className="space-y-4" noValidate><CardThemeSelector selectedTheme={formData.theme} onSelectTheme={setTheme} /><label className="block space-y-1 text-sm font-semibold text-[#555]">Kart Üzerindeki İsim<input name="cardHolder" value={formData.cardHolder} onChange={handleNameChange} className={inputClass} placeholder="Örn: MELİH YILMAZ" />{errors.cardHolder && <span className="text-xs text-red-600">{errors.cardHolder}</span>}</label><label className="block space-y-1 text-sm font-semibold text-[#555]">Kart Numarası<input name="cardNumber" inputMode="numeric" value={formData.cardNumber} onChange={handleCardNumberChange} className={inputClass} placeholder="1234 5678 1234 5678" />{errors.cardNumber && <span className="text-xs text-red-600">{errors.cardNumber}</span>}</label><div className="grid gap-4 sm:grid-cols-2"><label className="block space-y-1 text-sm font-semibold text-[#555]">Son Kullanma<input name="expiry" value={formData.expiry} onChange={handleExpiryChange} className={inputClass} placeholder="AA/YY" />{errors.expiry && <span className="text-xs text-red-600">{errors.expiry}</span>}</label><label className="block space-y-1 text-sm font-semibold text-[#555]">CVV<input name="cvv" type="password" value={formData.cvv} onChange={handleCvvChange} className={inputClass} placeholder="•••" />{errors.cvv && <span className="text-xs text-red-600">{errors.cvv}</span>}</label></div><div className="flex justify-end gap-2"><button type="button" onClick={() => setIsModalOpen(false)} className="rounded-lg bg-[#f3f3f3] px-4 py-2.5 text-sm font-semibold text-[#555]">Vazgeç</button><button type="submit" className="rounded-lg bg-[#b6349a] px-4 py-2.5 text-sm font-semibold text-white">Demo Kartı Kaydet</button></div></form></div></div>}
    {cardToDelete && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" onClick={() => setCardToDelete(null)}><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><h3 className="text-lg font-bold text-[#111]">Kartı silmek istediğinize emin misiniz?</h3><p className="mt-2 text-sm text-[#777]">{cardToDelete.maskedNumber} kartı silinecek. Bu işlem geri alınamaz.</p><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setCardToDelete(null)} className="rounded-lg bg-[#f3f3f3] px-4 py-2.5 text-sm font-semibold text-[#555]">Vazgeç</button><button type="button" onClick={removeCard} className="rounded-lg bg-red-600 px-4 py-2.5 text-sm font-semibold text-white">Evet, Kartı Sil</button></div></div></div>}
  </div>;
}
